### ISSUE TITLE
Migrate hi locale

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns-typescriptify#176]
Migrate [`hi` locale](https://github.com/date-fns/date-fns/tree/master/src/locale/hi) to TypeScript.

**Comment by minitesh** [comment]
@kossnocorp I am working on this

**Comment by minitesh** [comment]
@kossnocorp 
I observed that there are different formats user for `formatDistanceLocale`
I was thinking if this can be generalized so that we can have a common models for all and ensure the type safety.

e.g.
Some use this format
`lessThanXSeconds: {
    singular: 'mindre än en sekund',
    plural: 'mindre än {{count}} sekunder'
}`

some use this
`lessThanXSeconds: {
    standalone: {
      one: 'weniger als 1 Sekunde',
      other: 'weniger als {{count}} Sekunden',
    },
    withPreposition: {
      one: 'weniger als 1 Sekunde',
      other: 'weniger als {{count}} Sekunden',
    },
}`

Some use this
`lessThanXSeconds: {
    one: 'bir saniyədən az',
    other: '{{count}} bir saniyədən az'
}`
